### ISSUE TITLE
lxc config string in config file is limited in 16 bytes

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#19]
lxc config string should be less than 16 bytes.
For example, if lxc.network.veth.pair is 'leebaokleebaok-0', container will start failed. 

Now, we use UserName-ID-Offset as lxc.network.veth.pair and this may exceed the limited length.

**Comment by caodg** [comment]
that means if we can not ask lxc change its 16 bytes setting, and probably we can not, we have to use a inner id, instead of he username, i.e., userid-id-offset. the userid could be 6 bytes long numerical, which means a max of 999,999 users, enough for an organisation? or 6 bytes long num+alphabet, a max of 36**6=2,176,782,336.

the inner id could be the key from the usertable.

**Comment by caodg** [comment]
or the ID in UserName-ID-Offset need not be a global id, but a local id, starting from 0 for each user.

**Comment by leebaok** [comment]
Now, just use ClusterID-ContainerID as lxc.network.veth.pair name
